version: '3.1'
services:
  app:
    container_name: GestionDeProjetStage
    image: gestiondeprojet3
    build: /target
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
  postgresql:
    image:  postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gestiondeprojet
